# docker-compose.yml

version: "3"

services:
  # Fragments microservice API server
  fragments:
    # Use a proper init process (tini)
    init: true
    # Build the Docker Image using the Dockerfile
    # and current directory as the build context
    build: .
    # Environment variables to use
    environment:
          - API_URL=http://localhost:8080
          - HTPASSWD_FILE=tests/.htpasswd
          - LOG_LEVEL=${LOG_LEVEL:-info}
          - AWS_REGION=us-east-1
          - AWS_S3_ENDPOINT_URL=http://localstack:4566
          - AWS_DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
          - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-fragments}
          - AWS_DYNAMODB_TABLE_NAME=${AWS_DYNAMODB_TABLE_NAME:-fragments}
    ports:
        - "8080:8080"
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      # Default port for DynamoDB Local is 8000
      - '8000:8000'
    # Run the database in memory
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']
# LocalStack for S3
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
